export const metricsDefinition = {
  netIncome: `The net income of a company is its total revenue minus its total expenses.`,
  ratioCostOfRevenue: `Place Holder`,
  burnRatio: `Generally speaking, the burn ratio is simply the percentage of a company's total cash reserves that is being spent each month. So, for example, if a company has $1 million in cash and is spending $100,000 of that each month, its burn ratio would be 10%.`,
  rAndDBudgetToRevenue: `Place Holder`,
  grossProfitMargin: `Place Holder`,
  netProfitMargin: `Place Holder`,
  priceToEarning: `Place Holder`,
  debtRatio: `Place Holder`,
  currentRatio: `Place Holder`,
  priceToFreeCashFlowsRatio: `Place Holder`,
  freeCashFlow: `Place Holder`,
  operatingCashFlow: `Place Holder`,
  freeCashFlowToNetIncome: `Place Holder`,
  operatingCFToCurrentLiabilities: `Place Holder`,
  dividendYield: `Place Holder`,
  incomeTaxToNetIncome: `Place Holder`,
  returnOnRetainedEarnings: `Place Holder`,
  marketCapChangeWithRetainedEarnings: `Place Holder`,
  meanNetIncomeGrowthRate: `Place Holder`,
  meanFCFGrowthRate: `Place Holder`,
  intrinsicValue: `Place Holder`,
}
